site_name: Chef Tutorial
pages:
  - Home: index.md
  - Introduction to Chef: 01_introduction.md
  - Resources and Recipes: 03_resources_and_recipies.md
  - Cookbooks: 04_cookbooks.md
  - TDD with Test Kitchen: 05_tdd_with_test_kitchen.md
  - Setting up a Multi Node Cluster: 06_multi_node_cluster_setup.md
  - Data Driven Cookbooks: 07_data_driven_cookbooks_attr_templates.md
  - Customizing Community Cookbooks: 08_customizing_community_cookbooks.md
  - Deploying Sysfoo App: 09_deployment.md
  - Roles: 10_roles.md
  - Search: 11_search.md
  - Environments: 12_environments.md
  - Chef Solo: 13-applying-with-solo.md
docs_dir: chapters
theme: readthedocs
site_url: https://chef-tutorial.schoolofdevops.com/
site_author: Gourav Shah
site_description: Chef Tutorial by School of Devops
google_analytics: ['UA-36802546-17', 'chef-tutorial.schoolofdevops.com']
repo_url: https://github.com/schoolofdevops/zero-to-chef
edit_uri: edit/master/chapters
copyright: Copyright @ 2017-2020 Gourav Shah, School of Devops. Some rights reserved. License CC BY-NC-SA
extra:
  social:
    - type: 'github'
      link: 'https://github.com/schoolofdevops'
    - type: 'twitter'
      link: 'https://twitter.com/gouravhah'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/gouravshah'
